@echo off
REM ****************************************************************************
REM Vivado (TM) v2022.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Sun Jul 09 17:43:22 +0530 2023
REM SW Build 3671981 on Fri Oct 14 05:00:03 MDT 2022
REM
REM IP Build 3669848 on Fri Oct 14 08:30:02 MDT 2022
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim zff_tb1_behav -key {Behavioral:sim_1:Functional:zff_tb1} -tclbatch zff_tb1.tcl -protoinst "protoinst_files/design_3.protoinst" -protoinst "protoinst_files/design_2.protoinst" -protoinst "protoinst_files/design_1.protoinst" -protoinst "protoinst_files/design_4.protoinst" -protoinst "protoinst_files/design_5.protoinst" -log simulate.log"
call xsim  zff_tb1_behav -key {Behavioral:sim_1:Functional:zff_tb1} -tclbatch zff_tb1.tcl -protoinst "protoinst_files/design_3.protoinst" -protoinst "protoinst_files/design_2.protoinst" -protoinst "protoinst_files/design_1.protoinst" -protoinst "protoinst_files/design_4.protoinst" -protoinst "protoinst_files/design_5.protoinst" -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
