# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/design_2/design_2.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2 || ORIG_REF_NAME==design_2} -quiet] -quiet

# IP: bd/design_2/ip/design_2_zadoff_chu_0_0_1/design_2_zadoff_chu_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_2_zadoff_chu_0_0 || ORIG_REF_NAME==design_2_zadoff_chu_0_0} -quiet] -quiet

# XDC: c:/Users/velic/OneDrive/Desktop/vitis-hls/Assignment_9/VIVADO/project_1/project_1.gen/sources_1/bd/design_2/design_2_ooc.xdc
