set sim_status(wrapc_needed)  1
set sim_status(bc_needed)     0
set sim_status(sc_needed)     0
set sim_status(pc_needed)     1
set sim_status(no_tb_pc_needed) 0
set sim_status(vhdl_needed)   0
set sim_status(vlog_needed)   1
set sim_status(bc_tb_needed)  0
set sim_status(bc_tb_new_needed)  0
set sim_status(cas_needed)    0
set sim_DirAutoSimRoot        "sim"
set sim_DirAutoSimTv          "sim/tv"
set sim_DirAutoSimBc          "sim/bc"
set sim_DirAutoSimSc          "sim/systemc"
set sim_DirAutoSimPostCheck   "sim/wrapc_pc"
set sim_DirAutoSimNoTbPc      "sim/no_tb_pc"
set sim_DirAutoSimCasSc       "sim/casc"
set sim_DirAutoSimVhdl        "sim/vhdl"
set sim_DirAutoSimVlog        "sim/verilog"
set sim_DirAutoSimVlogGate    "sim/verilog.gate"
set sim_DirAutoSimWrapc       "sim/wrapc"
set sim_WorkingDir            "../.."
set sim_ConstFileTvIn         "cyclic_prefix_removal.autotvin.dat"
set sim_ConstFileTvOut        "cyclic_prefix_removal.autotvout.dat"
set sim_ConstFileHdlTvIn      "cyclic_prefix_removal.hdltvin.dat"
set sim_ConstFileHdlTvOut     "cyclic_prefix_removal.hdltvout.dat"
set sim_GateLevelSim          0
set sim_GTool                 "xsim"
set sim_GAutowrap             1
set sim_GTvIn                 "../../sim/tv/cyclic_prefix_removal.autotvin.dat"
set sim_GTvOut                "../../sim/tv/cyclic_prefix_removal.autotvout.dat"
set sim_GHdlTvIn              ""
set sim_GHdlTvOut             ""
